<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="TUnit" />
    <PackageReference Include="TUnit.Mocks" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\api\McpGateway.Api\McpGateway.Api.csproj" />
  </ItemGroup>

</Project>
