// <auto-generated />
using System;
using McpGateway.Core.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace McpGateway.Core.Persistence.Migrations
{
    [DbContext(typeof(GatewayDbContext))]
    [Migration("20260724144128_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("McpGateway.Core.Domain.AuditEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("ClientName")
                        .HasColumnType("TEXT")
                        .HasColumnName("client_name");

                    b.Property<string>("Input")
                        .HasColumnType("TEXT")
                        .HasColumnName("input");

                    b.Property<long>("LatencyMs")
                        .HasColumnType("INTEGER")
                        .HasColumnName("latency_ms");

                    b.Property<string>("Output")
                        .HasColumnType("TEXT")
                        .HasColumnName("output");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("TEXT")
                        .HasColumnName("timestamp");

                    b.Property<string>("ToolName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("tool_name");

                    b.Property<string>("UpstreamName")
                        .HasColumnType("TEXT")
                        .HasColumnName("upstream_name");

                    b.HasKey("Id")
                        .HasName("pk_audit_entries");

                    b.HasIndex("Timestamp", "ClientName", "ToolName")
                        .HasDatabaseName("ix_audit_entries_timestamp_client_name_tool_name");

                    b.ToTable("audit_entries", (string)null);
                });

            modelBuilder.Entity("McpGateway.Core.Domain.GatewayClient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("AuthKind")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("auth_kind");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Secret")
                        .HasColumnType("TEXT")
                        .HasColumnName("secret");

                    b.HasKey("Id")
                        .HasName("pk_gateway_clients");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_gateway_clients_name");

                    b.ToTable("gateway_clients", (string)null);
                });

            modelBuilder.Entity("McpGateway.Core.Domain.ToolOverride", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER")
                        .HasColumnName("enabled");

                    b.Property<string>("OverrideDescription")
                        .HasColumnType("TEXT")
                        .HasColumnName("override_description");

                    b.Property<string>("OverrideName")
                        .HasColumnType("TEXT")
                        .HasColumnName("override_name");

                    b.Property<string>("ToolName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("tool_name");

                    b.Property<Guid>("UpstreamId")
                        .HasColumnType("TEXT")
                        .HasColumnName("upstream_id");

                    b.HasKey("Id")
                        .HasName("pk_tool_overrides");

                    b.HasIndex("UpstreamId", "ToolName")
                        .IsUnique()
                        .HasDatabaseName("ix_tool_overrides_upstream_id_tool_name");

                    b.ToTable("tool_overrides", (string)null);
                });

            modelBuilder.Entity("McpGateway.Core.Domain.Upstream", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Args")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("args");

                    b.Property<string>("AuthConfigJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("auth_config_json");

                    b.Property<string>("AuthKind")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("auth_kind");

                    b.Property<string>("Command")
                        .HasColumnType("TEXT")
                        .HasColumnName("command");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER")
                        .HasColumnName("enabled");

                    b.Property<string>("Endpoint")
                        .HasColumnType("TEXT")
                        .HasColumnName("endpoint");

                    b.Property<string>("Environment")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("environment");

                    b.Property<string>("Headers")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("headers");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Secret")
                        .HasColumnType("TEXT")
                        .HasColumnName("secret");

                    b.Property<string>("Transport")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("transport");

                    b.HasKey("Id")
                        .HasName("pk_upstreams");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_upstreams_name");

                    b.ToTable("upstreams", (string)null);
                });

            modelBuilder.Entity("McpGateway.Core.Domain.ToolOverride", b =>
                {
                    b.HasOne("McpGateway.Core.Domain.Upstream", null)
                        .WithMany()
                        .HasForeignKey("UpstreamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tool_overrides_upstreams_upstream_id");
                });
#pragma warning restore 612, 618
        }
    }
}
